# Generated by Django 4.2.7 on 2024-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('webapp', '0012_article_author_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes_article', to='accounts.profile', verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes_comment', to='accounts.profile', verbose_name='Лайки'),
        ),
    ]
