# Generated by Django 4.2.7 on 2024-01-31 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0015_remove_comment_likes_alter_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='loved_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
